# -*- coding: utf-8 -*-
"""notebook-predict.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hD-SY0KofCQJQKQcrpJN1ZmlHDsE4zLy

# Proyek Akhir: Sistem Rekomendasi Karier untuk Siswa

**Submission Machine Learning Terapan – Dicoding**

---

Halo! Di notebook ini, aku bakal bangun **sistem rekomendasi karier** untuk siswa SMA berdasarkan profil akademik mereka.

Idenya simpel: jika terdapat siswa baru yang bingung ingin menjadi apa setelah lulus, sistem ini bisa memberikan saran karier yang sesuai dilihat dari nilai-nilai pelajaran, jam belajar, ekskul, dll.

- Dataset **Student Studeis Recommendation** dari Kaggle (link: https://www.kaggle.com/datasets/noorsaeed/student-studeis-recommendation)
- Dua pendekatan rekomendasi:
  1. **Content-Based Filtering** — menggunakan cosine similarity untuk mencari siswa yang profilnya mirip
  2. **Collaborative Filtering** — menggunakan neural network untuk belajar pola siswa-karier

## 1. Import Library
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import MinMaxScaler, LabelEncoder
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics import (precision_score, recall_score, f1_score,
                             roc_auc_score, accuracy_score)

import tensorflow as tf
from tensorflow.keras import layers, Model
from tensorflow.keras.optimizers import Adam

import warnings
warnings.filterwarnings("ignore")

# Set random seed biar hasilnya reproducible
SEED = 42
np.random.seed(SEED)
tf.random.set_seed(SEED)

print("Library siap dipakai!")
print("TensorFlow version:", tf.__version__)

"""## 2. Data Loading

"""

df = pd.read_csv("student-scores.csv")
print(f"Shape: {df.shape}")
print(f"Total kolom: {df.shape[1]}")
print(f"Total siswa: {df.shape[0]}")
df.head()

"""## 3. Exploratory Data Analysis (EDA)

### 3.1 Info Dataset
"""

df.info()

"""### 3.2 Cek Missing Values dan Duplikat

"""

print("Missing values per kolom:")
print(df.isnull().sum())
print(f"\nTotal baris duplikat: {df.duplicated().sum()}")

"""Tidak ada missing values dan nggak ada duplikat.

### 3.3 Statistik Nilai Mata Pelajaran
"""

score_cols = ["math_score", "history_score", "physics_score", "chemistry_score",
              "biology_score", "english_score", "geography_score"]
df[score_cols].describe().round(2)

"""### 3.4 Distribusi Cita-cita Karier

Aku penasaran karier apa aja yang paling banyak diminati siswa.
"""

career_counts = df["career_aspiration"].value_counts()
print("Distribusi cita-cita karier:")
print(career_counts)
print(f"\nTotal jenis karier: {df['career_aspiration'].nunique()}")

"""- Software Engineer dan Business Owner paling populer
- Ada 223 siswa yang masih "Unknown" — akan menghapus kolom kolom ini karena tidak bisa digunakan untuk training
- Total terdapat 17 jenis karier

### 3.5 Visualisasi
"""

fig, axes = plt.subplots(2, 2, figsize=(15, 10))

# 1. Distribusi cita-cita karier (bar chart)
career_counts.plot(kind="barh", ax=axes[0, 0], color="steelblue")
axes[0, 0].set_title("Distribusi Cita-cita Karier", fontsize=12, fontweight="bold")
axes[0, 0].set_xlabel("Jumlah Siswa")
axes[0, 0].invert_yaxis()

# 2. Distribusi nilai matematika
axes[0, 1].hist(df["math_score"], bins=30, color="coral", edgecolor="black")
axes[0, 1].set_title("Distribusi Nilai Matematika", fontsize=12, fontweight="bold")
axes[0, 1].set_xlabel("Nilai")
axes[0, 1].set_ylabel("Jumlah Siswa")

# 3. Boxplot semua nilai
df[score_cols].boxplot(ax=axes[1, 0])
axes[1, 0].set_title("Boxplot Semua Mata Pelajaran", fontsize=12, fontweight="bold")
axes[1, 0].set_ylabel("Nilai")
axes[1, 0].tick_params(axis="x", rotation=45)

# 4. Distribusi jam belajar mingguan
axes[1, 1].hist(df["weekly_self_study_hours"], bins=20, color="mediumseagreen", edgecolor="black")
axes[1, 1].set_title("Distribusi Jam Belajar Mingguan", fontsize=12, fontweight="bold")
axes[1, 1].set_xlabel("Jam per Minggu")
axes[1, 1].set_ylabel("Jumlah Siswa")

plt.tight_layout()
plt.savefig("eda_visualization.png", dpi=80, bbox_inches="tight")
plt.show()

"""-  Karier paling populer: Software Engineer, Business Owner, Banker
-  Nilai matematika cenderung tersebar dari 50-100, dengan rata-rata ~70-80
-  Semua mata pelajaran memiliki range nilai yang mirip (sekitar 50-100)
-  Sebagian besar siswa belajar 5-30 jam per minggu

### 3.6 Korelasi Antar Nilai Mata Pelajaran
"""

plt.figure(figsize=(10, 7))
corr = df[score_cols].corr()
sns.heatmap(corr, annot=True, fmt=".2f", cmap="coolwarm", center=0,
            square=True, linewidths=0.5, cbar_kws={"shrink": .8})
plt.title("Korelasi Antar Nilai Mata Pelajaran", fontsize=13, fontweight="bold")
plt.tight_layout()
plt.savefig("correlation_heatmap.png", dpi=80, bbox_inches="tight")
plt.show()

"""Korelasi antar mata pelajaran cukup rendah (kebanyakan < 0.3). Ini berarti tiap mata pelajaran mempunyai pola sendiri-sendiri, dan tidak otomatis siswa yang unggul di satu pelajaran juga unggul di pelajaran lain.

## 4. Data Preparation

### 4.1 Hapus Siswa dengan Cita-cita "Unknown"
"""

print(f"Sebelum: {df.shape}")
df = df[df["career_aspiration"] != "Unknown"].reset_index(drop=True)
print(f"Sesudah: {df.shape}")

"""### 4.2 Hapus Kolom yang Tidak Relevan

"""

df_clean = df.drop(columns=["first_name", "last_name", "email"]).copy()
print("Kolom yang dipakai:", df_clean.columns.tolist())

"""### 4.3 Encoding Boolean → Integer


"""

df_clean["gender"] = df_clean["gender"].map({"male": 0, "female": 1})
df_clean["part_time_job"] = df_clean["part_time_job"].astype(int)
df_clean["extracurricular_activities"] = df_clean["extracurricular_activities"].astype(int)
df_clean.head()

"""### 4.4 Normalisasi Fitur (Min-Max Scaling)

"""

feature_cols = ["gender", "part_time_job", "absence_days", "extracurricular_activities",
                "weekly_self_study_hours", "math_score", "history_score", "physics_score",
                "chemistry_score", "biology_score", "english_score", "geography_score"]

scaler = MinMaxScaler()
features_scaled = scaler.fit_transform(df_clean[feature_cols])

print(f"Shape feature matrix: {features_scaled.shape}")
print(f"\nContoh hasil normalisasi (siswa pertama):")
for col, val in zip(feature_cols, np.round(features_scaled[0], 3)):
    print(f"  {col}: {val}")

"""### 4.5 Encoding Cita-cita Karier (Label Encoding)

"""

career_encoder = LabelEncoder()
df_clean["career_id"] = career_encoder.fit_transform(df_clean["career_aspiration"])

print("Mapping career → career_id:")
for i, c in enumerate(career_encoder.classes_):
    print(f"  {i}: {c}")
n_careers = df_clean["career_id"].nunique()
print(f"\nTotal karier: {n_careers}")

"""### 4.6 Membuat Data Interaksi untuk Collaborative Filtering

- Setiap siswa "menyukai" cita-citanya sendiri (label = 1)
- Setiap siswa "tidak menyukai" karier random lainnya (label = 0)

Ini disebut **negative sampling** — teknik standar di rekomendasi implicit feedback.
"""

np.random.seed(SEED)

# Positive: siswa + cita-citanya = 1
positive = df_clean[["id", "career_id"]].copy()
positive["label"] = 1.0

# Negative: 4 karier random per siswa = 0
N_NEG = 4
neg_samples = []
for _, row in df_clean.iterrows():
    sid = row["id"]
    true_cid = row["career_id"]
    # Pilih karier yang BUKAN cita-cita siswa ini
    candidates = [c for c in range(n_careers) if c != true_cid]
    neg_cids = np.random.choice(candidates, size=N_NEG, replace=False)
    for ncid in neg_cids:
        neg_samples.append({"id": sid, "career_id": ncid, "label": 0.0})

negative = pd.DataFrame(neg_samples)
interactions = pd.concat([positive, negative], ignore_index=True)
interactions = interactions.sample(frac=1, random_state=SEED).reset_index(drop=True)

print(f"Total interaksi: {len(interactions)}")
print(f"  Positive (label=1): {(interactions['label']==1).sum()}")
print(f"  Negative (label=0): {(interactions['label']==0).sum()}")
print(f"\nRasio positive:negative = 1:{N_NEG}")

"""### 4.7 Encoding Student ID


"""

student_ids = df_clean["id"].unique()
student_to_idx = {s: i for i, s in enumerate(student_ids)}
idx_to_student = {i: s for s, i in student_to_idx.items()}

interactions["student_idx"] = interactions["id"].map(student_to_idx)
n_students = len(student_ids)
print(f"Total siswa unik: {n_students}")

"""### 4.8 Train-Test Split

80% untuk training dan 20% untuk validation.
"""

shuffled = interactions.sample(frac=1, random_state=SEED).reset_index(drop=True)
X_cf = shuffled[["student_idx", "career_id"]].values
y_cf = shuffled["label"].values

train_n = int(0.8 * len(shuffled))
X_train, X_val = X_cf[:train_n], X_cf[train_n:]
y_train, y_val = y_cf[:train_n], y_cf[train_n:]

print(f"Train size: {len(X_train)}")
print(f"Val size  : {len(X_val)}")

"""## 5. Modeling Tahap 1: Content-Based Filtering

Mencari siswa-siswa yang profilnya paling mirip dengan siswa target, lalu rekomendasikan karier yang paling sering muncul di antara mereka. Menggunakan **cosine similarity** untuk ngitung kemiripan profil.


"""

# Hitung cosine similarity matrix antar siswa
sim_matrix = cosine_similarity(features_scaled)
print(f"Similarity matrix shape: {sim_matrix.shape}")
print(f"\nContoh similarity siswa 0 dengan 5 siswa pertama:")
print(np.round(sim_matrix[0][:5], 4))

# Mapping student_id ke posisi di matrix
sid_to_pos = {sid: i for i, sid in enumerate(df_clean["id"].values)}


def recommend_career_cbf(student_id, top_n=5, top_k_neighbors=50):
    if student_id not in sid_to_pos:
        return f"Siswa {student_id} tidak ditemukan."

    pos = sid_to_pos[student_id]
    sims = sim_matrix[pos].copy()
    sims[pos] = -np.inf  # exclude diri sendiri

    neighbor_idx = sims.argsort()[::-1][:top_k_neighbors]
    neighbor_careers = df_clean.iloc[neighbor_idx]["career_aspiration"].values
    neighbor_sims = sim_matrix[pos][neighbor_idx]

    # Weighted voting
    score_dict = {}
    for c, s in zip(neighbor_careers, neighbor_sims):
        score_dict[c] = score_dict.get(c, 0.0) + s

    sorted_careers = sorted(score_dict.items(), key=lambda x: x[1], reverse=True)
    return pd.DataFrame(sorted_careers[:top_n], columns=["career_aspiration", "score"])


# Demo: rekomendasi untuk siswa pertama
demo_id = df_clean["id"].iloc[0]
demo_row = df_clean[df_clean["id"] == demo_id].iloc[0]

print(f"=== Profil Siswa ID {demo_id} ===")
print(f"Cita-cita asli  : {demo_row['career_aspiration']}")
print(f"Math score      : {demo_row['math_score']}")
print(f"Physics score   : {demo_row['physics_score']}")
print(f"English score   : {demo_row['english_score']}")
print(f"Study hours/week: {demo_row['weekly_self_study_hours']}")
print()
print("Top-5 Rekomendasi Karier:")
print(recommend_career_cbf(demo_id, top_n=5).to_string(index=False))

"""## 6. Modeling Tahap 2: Collaborative Filtering (Neural Network)

Menggunakan neural network dengan **embedding layer** untuk kolom siswa dan karier. Model belajar representasi vektor masing-masing dari pola interaksi siswa-karier.

Arsitektur model:
```
[student_id] → Student Embedding (32-dim) ┐
                                          ├→ Dot Product → +bias → Sigmoid → Skor [0,1]
[career_id]  → Career Embedding (32-dim)  ┘
```

Output skor [0,1] menyatakan seberapa cocok pasangan (siswa, karier) — jika mendekati 1 berarti sangat sesuai.
"""

EMBED_DIM = 32


class CareerRecommenderNet(Model):

    def __init__(self, n_students, n_careers, embed_dim, **kwargs):
        super().__init__(**kwargs)
        self.student_emb = layers.Embedding(
            n_students, embed_dim,
            embeddings_initializer="he_normal",
            embeddings_regularizer=tf.keras.regularizers.l2(1e-6)
        )
        self.student_bias = layers.Embedding(n_students, 1)
        self.career_emb = layers.Embedding(
            n_careers, embed_dim,
            embeddings_initializer="he_normal",
            embeddings_regularizer=tf.keras.regularizers.l2(1e-6)
        )
        self.career_bias = layers.Embedding(n_careers, 1)

    def call(self, inputs):
        s_vec = self.student_emb(inputs[:, 0])
        s_b = self.student_bias(inputs[:, 0])
        c_vec = self.career_emb(inputs[:, 1])
        c_b = self.career_bias(inputs[:, 1])
        dot = tf.reduce_sum(s_vec * c_vec, axis=1, keepdims=True)
        x = dot + s_b + c_b
        return tf.nn.sigmoid(x)


model_cf = CareerRecommenderNet(n_students, n_careers, EMBED_DIM)
model_cf.compile(
    loss=tf.keras.losses.BinaryCrossentropy(),
    optimizer=Adam(learning_rate=0.003),
    metrics=[tf.keras.metrics.BinaryAccuracy(name="acc"),
             tf.keras.metrics.AUC(name="auc")]
)

print(f"Student embedding: ({n_students}, {EMBED_DIM})")
print(f"Career embedding : ({n_careers}, {EMBED_DIM})")

# Training dengan early stopping biar nggak overfit
early_stop = tf.keras.callbacks.EarlyStopping(
    monitor="val_auc", patience=10, mode="max",
    restore_best_weights=True, verbose=1
)

history = model_cf.fit(
    x=X_train, y=y_train,
    validation_data=(X_val, y_val),
    batch_size=64, epochs=50,
    callbacks=[early_stop],
    verbose=2
)

# Plot learning curve
fig, axes = plt.subplots(1, 3, figsize=(16, 4))

axes[0].plot(history.history["loss"], label="train")
axes[0].plot(history.history["val_loss"], label="val")
axes[0].set_title("Loss"); axes[0].set_xlabel("Epoch"); axes[0].legend()
axes[0].grid(alpha=0.3)

axes[1].plot(history.history["acc"], label="train")
axes[1].plot(history.history["val_acc"], label="val")
axes[1].set_title("Accuracy"); axes[1].set_xlabel("Epoch"); axes[1].legend()
axes[1].grid(alpha=0.3)

axes[2].plot(history.history["auc"], label="train")
axes[2].plot(history.history["val_auc"], label="val")
axes[2].set_title("AUC-ROC"); axes[2].set_xlabel("Epoch"); axes[2].legend()
axes[2].grid(alpha=0.3)

plt.tight_layout()
plt.savefig("training_history.png", dpi=80, bbox_inches="tight")
plt.show()

"""## 7. Evaluation

### 7.1 Evaluasi Content-Based
"""

def evaluate_cbf_precision(top_n=5, top_k_neighbors=50):
    """Hitung Hit Rate@N untuk Content-Based."""
    n = len(df_clean)
    careers_arr = df_clean["career_aspiration"].values
    hits = 0

    for i in range(n):
        sims = sim_matrix[i].copy()
        sims[i] = -np.inf
        neighbor_idx = sims.argsort()[::-1][:top_k_neighbors]
        neighbor_careers = careers_arr[neighbor_idx]
        neighbor_sims = sim_matrix[i][neighbor_idx]

        score_dict = {}
        for c, s in zip(neighbor_careers, neighbor_sims):
            score_dict[c] = score_dict.get(c, 0.0) + s
        sorted_careers = sorted(score_dict.items(), key=lambda x: x[1], reverse=True)
        top_careers = [c for c, _ in sorted_careers[:top_n]]

        if careers_arr[i] in top_careers:
            hits += 1
    return hits / n


print("Evaluasi Content-Based Filtering:")
cbf_top1 = evaluate_cbf_precision(top_n=1, top_k_neighbors=50)
cbf_top3 = evaluate_cbf_precision(top_n=3, top_k_neighbors=50)
cbf_top5 = evaluate_cbf_precision(top_n=5, top_k_neighbors=50)
cbf_top7 = evaluate_cbf_precision(top_n=7, top_k_neighbors=50)
cbf_top10 = evaluate_cbf_precision(top_n=10, top_k_neighbors=50)

print(f"Hit Rate Top-1  : {cbf_top1:.4f}")
print(f"Hit Rate Top-3  : {cbf_top3:.4f}")
print(f"Hit Rate Top-5  : {cbf_top5:.4f}")
print(f"Hit Rate Top-7  : {cbf_top7:.4f}")
print(f"Hit Rate Top-10 : {cbf_top10:.4f}")

"""### 7.2 Evaluasi Collaborative Filtering"""

# Prediksi pada validation set
y_pred_val = model_cf.predict(X_val, verbose=0).flatten()
y_pred_class = (y_pred_val >= 0.5).astype(int)

cf_acc = accuracy_score(y_val, y_pred_class)
cf_prec = precision_score(y_val, y_pred_class, zero_division=0)
cf_rec = recall_score(y_val, y_pred_class, zero_division=0)
cf_f1 = f1_score(y_val, y_pred_class, zero_division=0)
cf_auc = roc_auc_score(y_val, y_pred_val)

print("Evaluasi Collaborative Filtering (klasifikasi binary):")
print(f"Akurasi  : {cf_acc:.4f}")
print(f"Precision: {cf_prec:.4f}")
print(f"Recall   : {cf_rec:.4f}")
print(f"F1-score : {cf_f1:.4f}")
print(f"AUC-ROC  : {cf_auc:.4f}")

def evaluate_cf_hit_rate_batch(top_ns=(1, 3, 5, 7, 10)):
    """Hitung Hit Rate@N untuk semua siswa secara batch (lebih cepat)."""
    all_pairs = []
    true_careers = []
    for _, row in df_clean.iterrows():
        sid = row["id"]
        s_idx = student_to_idx[sid]
        for cid in range(n_careers):
            all_pairs.append([s_idx, cid])
        true_careers.append(row["career_id"])

    all_pairs = np.array(all_pairs)
    all_scores = model_cf.predict(all_pairs, batch_size=1024, verbose=0).flatten()

    n = len(df_clean)
    scores_matrix = all_scores.reshape(n, n_careers)

    results = {}
    for top_n in top_ns:
        hits = 0
        for i, true_cid in enumerate(true_careers):
            top_cids = scores_matrix[i].argsort()[::-1][:top_n]
            if true_cid in top_cids:
                hits += 1
        results[top_n] = hits / n
    return results


print("Hit Rate Collaborative Filtering:")
cf_hits = evaluate_cf_hit_rate_batch(top_ns=(1, 3, 5, 7, 10))
cf_top1, cf_top3, cf_top5 = cf_hits[1], cf_hits[3], cf_hits[5]
cf_top7, cf_top10 = cf_hits[7], cf_hits[10]

print(f"Hit Rate Top-1  : {cf_top1:.4f}")
print(f"Hit Rate Top-3  : {cf_top3:.4f}")
print(f"Hit Rate Top-5  : {cf_top5:.4f}")
print(f"Hit Rate Top-7  : {cf_top7:.4f}")
print(f"Hit Rate Top-10 : {cf_top10:.4f}")

"""## 8. Demo Top-N Recommendation

"""

def recommend_career_cf(student_id, top_n=5):
    """Top-N rekomendasi karier dari Collaborative Filtering."""
    if student_id not in student_to_idx:
        return f"Siswa {student_id} tidak ditemukan."

    s_idx = student_to_idx[student_id]
    pairs = np.array([[s_idx, cid] for cid in range(n_careers)])
    scores = model_cf.predict(pairs, verbose=0).flatten()
    top_idx = scores.argsort()[::-1][:top_n]

    return pd.DataFrame({
        "career_aspiration": career_encoder.inverse_transform(top_idx),
        "predicted_score": np.round(scores[top_idx], 4)
    })


# Demo untuk 3 siswa
for demo_id in [1, 100, 1000]:
    if demo_id not in sid_to_pos:
        continue
    row = df_clean[df_clean["id"] == demo_id].iloc[0]
    print(f"\n{'='*65}")
    print(f">>> Siswa ID {demo_id} <<<")
    print(f"{'='*65}")
    print(f"Profil:")
    print(f"  Math: {row['math_score']}, Physics: {row['physics_score']}, English: {row['english_score']}")
    print(f"  Study hours/week: {row['weekly_self_study_hours']}")
    print(f"  Cita-cita asli: {row['career_aspiration']}")
    print(f"\nRekomendasi Content-Based (Top-5):")
    print(recommend_career_cbf(demo_id, 5).to_string(index=False))
    print(f"\nRekomendasi Collaborative Filtering (Top-5):")
    print(recommend_career_cf(demo_id, 5).to_string(index=False))

"""## 9. Ringkasan Hasil Evaluasi"""

summary = pd.DataFrame({
    "Metrik": [
        "Content-Based: Hit Rate Top-1",
        "Content-Based: Hit Rate Top-3",
        "Content-Based: Hit Rate Top-5",
        "Content-Based: Hit Rate Top-7",
        "Content-Based: Hit Rate Top-10",
        "Collaborative Filtering: Akurasi",
        "Collaborative Filtering: Precision",
        "Collaborative Filtering: Recall",
        "Collaborative Filtering: F1-score",
        "Collaborative Filtering: AUC-ROC",
        "Collaborative Filtering: Hit Rate Top-1",
        "Collaborative Filtering: Hit Rate Top-3",
        "Collaborative Filtering: Hit Rate Top-5",
        "Collaborative Filtering: Hit Rate Top-7",
        "Collaborative Filtering: Hit Rate Top-10",
    ],
    "Nilai": [
        f"{cbf_top1:.4f}",
        f"{cbf_top3:.4f}",
        f"{cbf_top5:.4f}",
        f"{cbf_top7:.4f}",
        f"{cbf_top10:.4f}",
        f"{cf_acc:.4f}",
        f"{cf_prec:.4f}",
        f"{cf_rec:.4f}",
        f"{cf_f1:.4f}",
        f"{cf_auc:.4f}",
        f"{cf_top1:.4f}",
        f"{cf_top3:.4f}",
        f"{cf_top5:.4f}",
        f"{cf_top7:.4f}",
        f"{cf_top10:.4f}",
    ]
})
summary